### ISSUE TITLE
[Bug] Wrong Python SDK package name in the dependencies list

### ISSUE THREAD

**Issue by Brycetlm** [diem/reference-wallet#13]
# 🐛 Bug

I followed the Readme of backend, used `./scripts/lrw.sh setup_environment # generate and register keys`, then this problem was shown:

```
ERROR: Requested diem-client-sdk from git+https://github.com/libra/client-sdk-python.git@7059a9ef03304c2790f78ce94eeadd4ccecb1e05#egg=client-python-sdk (from -r /tmp/pipenv-flypqxv3-requirements/pipenv-e88kn3gp-requirement.txt (line 1)) has different name in metadata: 'diem-client-sdk'
ERROR: Couldn't install package: client-python-sdk
 Package installation failed...
```

## System information

**Please complete the following information:**
- 

## Additional context

the given website(https://github.com/libra/client-sdk-python.git@7059a9ef03304c2790f78ce94eeadd4ccecb1e05#egg=client-python-sdk) is 404, 
so I use 'pip install diem-client-sdk' and delete the related info in pipfile.lock and pipfile, and it seems work.

**Comment by yanivmo** [comment]
Thanks @Brycetlm for opening the issue.
Could you, please, elaborate which command you were running when you encountered the error?

**Comment by Brycetlm** [comment]
> Thanks @Brycetlm for opening the issue.
> Could you, please, elaborate which command you were running when you encountered the error?
So quickly！ I followed the Readme of backend, used **"./scripts/lrw.sh setup_environment  # generate and register keys",** then this problem was shown.
Eventually it worked after I deleted the related part in pipfile.lock of both backend and liquidity and  installed sdk manually

**Comment by yanivmo** [comment]
> > Thanks @Brycetlm for opening the issue.
> > Could you, please, elaborate which command you were running when you encountered the error?
> > So quickly！ I followed the Readme of backend, used **"./scripts/lrw.sh setup_environment  # generate and register keys",** then this problem was shown.
> > Eventually it worked after I deleted the related part in pipfile.lock of both backend and liquidity and  installed sdk manually

The fix will land in the following day or two. Thanks again for your help.
